# OP Method Algorithms
algorithms = {
    'corner': ["R", "U'", "R'", "U'", "R", "U", "R'", "F'", "R", "U", "R'", "U'", "R'", "F", "R"],
    'edge T': ["R", "U", "R'", "U'", "R'", "F", "R2", "U'", "R'", "U'", "R", "U", "R'", "F'"], 
    'edge J': ["R", "U", "R'", "F'", "R", "U", "R'", "U'", "R'", "F", "R2", "U'", "R'", "U'"],
    'parity': ["U'", "L", "U2", "L'", "U2", "L", "F'", "L'", "U'", "L", "U", "L", "F", "L2", "U2"]
}

# OP Method setup moves for letters
letters = {
    'A': [*algorithms['corner']],
    'B': ["R", "D'", *algorithms['corner'], "D", "R'"],
    'C': ["F", *algorithms['corner'], "F'"],
    'D': ["F", "R'", *algorithms['corner'], "R", "F'"],
    'E': ["F'", "D", *algorithms['corner'], "D'", "F"],
    'F': ["F2", "D", *algorithms['corner'], "D'", "F2"],
    'G': ["D", "R", *algorithms['corner'], "R'", "D'"],
    'H': ["D", *algorithms['corner'], "D'"],
    'I': ["R'", *algorithms['corner'], "R"],
    "J": ["R2", *algorithms['corner'], "R2"],
    "K": ["R", *algorithms['corner'], "R'"],
    "L": [*algorithms['corner']],
    "M": ["R'", "F", *algorithms['corner'], "F'", "R"],
    "N": [*algorithms['corner']],
    "O": ["D'", "R", *algorithms['corner'], "R'", "D"],
    "P": ["D'", *algorithms['corner'], "D"],
    "Q": [*algorithms['corner']],
    "R": ["F2", *algorithms['corner'], "F2"],
    "S": ["D2", "R", *algorithms['corner'], "R'", "D2"],
    "T": ["D2", *algorithms['corner'], "D2"],
    "U": ["F'", *algorithms['corner'], "F"],
    "V": ["D'", "F'", *algorithms['corner'], "F", "D"],
    "W": ["D2", "F'", *algorithms['corner'], "F", "D2"],
    "X": ["D", "F", *algorithms['corner'], "F'", "D'"],
    'a': ["l2", "D'", "L2", *algorithms['edge T'], "L2", "D", "l2"],
    'b': [*algorithms['edge T']],
    'c': [*algorithms['edge J']],
    'd': [*algorithms['edge T']],
    'e': ["l", "D'", "L2", *algorithms['edge T'], "L2", "D", "l'"],
    'f': ["d2", "L", *algorithms['edge T'], "L'", "d2"],
    'g': ["l'", *algorithms['edge J'], "l"],
    'h': ["L'", *algorithms['edge T'], "L"],
    'i': [*algorithms['edge T']],
    'j': ["d", "L", *algorithms['edge T'], "L'", "d'"],
    'k': ["D'", "l'", *algorithms['edge J'], "l", "D"],
    'l': ["d'", "L'", *algorithms['edge T'], "L", "d"],
    'm': ["l", *algorithms['edge J'], "l'"],
    'n': ["L", *algorithms['edge T'], "L'"],
    'o': ["D2", "l'", *algorithms['edge J'], "l", "D2"],
    'p': ["d2", "L'", *algorithms['edge T'], "L", "d2"],
    'q': ["L2", "d", "l'", *algorithms['edge J'], "l", "d'", "L2"],
    'r': ["d'", "L", *algorithms['edge T'], "L'", "d"],
    's': ["D", "l'", *algorithms['edge J'], "l", "D'"],
    't': ["d", "L'", *algorithms['edge T'], "L", "d'"],
    'u': ["D'", "L2", *algorithms['edge T'], "L2", "D"],
    'v': ["D2", "L2", *algorithms['edge T'], "L2", "D2"],
    'w': ["D", "L2", *algorithms['edge T'], "L2", "D'"],
    'x': ["L2", *algorithms['edge T'], "L2"]

}
